/*
 * =====================================================================================
 *
 *       Filename: strtbl.jinja2.hpp
 *        Created: 12/28/2018 03:25:41
 *    Description: 
 *
 *        Version: 1.0
 *       Revision: none
 *       Compiler: gcc
 *
 *         Author: ANHONG
 *          Email: anhonghe@gmail.com
 *   Organization: USTC
 *
 * =====================================================================================
 */

#pragma once
namespace libnvc
{
    // don't modify
    // entries generated by jinja2

    constexpr static const char * g_nvim_api_string_tbl[]
    {
        // put the zero index as reserved
        nullptr,

        // requests
{% for req in nvim_reqs %}
        "req::{{req.name}},"
{% endfor %}

        // notifications
        "notif::test",
    };
}
